### ISSUE TITLE
Some prompts have incorrect translations

### ISSUE THREAD

**Issue by sowelilili** [lipu-linku/ilo#11]
I've noticed the following prompts:

> tenpo poka la, sina toki e seme lon toki pona?
> ||What do you use to travel?||

> sina ken tawa ma ale la, sina tawa seme?
> ||What's the last thing you talked about in toki pona?||

it seems highly likely that the translations for these are the wrong way around.

**Comment by gregdan3** [comment]
Oh- thanks for catching this! Looks like we've fixed it since you posted. Sorry for not saying something sooner!
