### ISSUE TITLE
New version of "insa pi supa lape"

### ISSUE THREAD

**Issue by slashdevslashurandom** [lipu-linku/ilo#2]
I updated my font "insa pi supa lape" to add support all the codepoints as specified in the [UCSUR description](https://www.kreativekorp.com/ucsur/charts/sitelen.html). This means all the "nimi ku suli", as well as some other non-pu words, are all supported now.

<https://gitlab.com/dev_urandom/insa-pi-supa-lape/-/releases> has the latest version.

**Comment by AcipenserSturio** [comment]
Updated
