### ISSUE TITLE
You cant revert to the default sp font after changing it to something else

### ISSUE THREAD

**Issue by ghost** [lipu-linku/ilo#4]
I have cycled through all of the options and none of them are the default. Please help

**Comment by AcipenserSturio** [comment]
The default font is linja sike - you should be able to select it in the menu

But its true that there is no indication that it's the default - we might want to work on that

**Comment by AcipenserSturio** [comment]
You can also use `/preferences reset` - but it resets everything, not just the font. (it was easier to implement at the time.)
